[book]
title = "Vault"
authors = ["Vadim Schultz"]
description = "Automatic document versioning"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/vadim-schultz/vault"
